import {
  AuditIcon,
  BriefcaseIcon,
  CoinsIcon,
  DashIcon,
  FeeIcon,
  GuarantorIcon,
  HandshakeIcon,
  KarmaIcon,
  LoanReqIcon,
  LoanIcon,
  PreferencesIcon,
  ReportsIcon,
  SavingsProdIcon,
  SavingsIcon,
  ServiceAccIcon,
  ServicesIcon,
  SettlementsIcon,
  TransIcon,
  UsersIcon,
  WhitelistIcon,
} from "./assets";

export const navigationData = {
  main: [{ id: "dashboard", label: "Dashboard", icon: DashIcon, href: "#" }],
  customers: [
    { id: "users", label: "Users", icon: UsersIcon, href: "/users" },
    { id: "guarantors", label: "Guarantors", icon: GuarantorIcon, href: "#" },
    { id: "loans", label: "Loans", icon: LoanIcon, href: "#" },
    {
      id: "decision-models",
      label: "Decision Models",
      icon: HandshakeIcon,
      href: "#",
    },
    { id: "savings", label: "Savings", icon: SavingsIcon, href: "#" },
    {
      id: "loan-requests",
      label: "Loan Requests",
      icon: LoanReqIcon,
      href: "#",
    },
    { id: "whitelist", label: "Whitelist", icon: WhitelistIcon, href: "#" },
    { id: "karma", label: "Karma", icon: KarmaIcon, href: "#" },
  ],
  businesses: [
    {
      id: "organization",
      label: "Organization",
      icon: BriefcaseIcon,
      href: "#",
    },
    { id: "loan-products", label: "Loan Products", icon: LoanIcon, href: "#" },
    {
      id: "savings-products",
      label: "Savings Products",
      icon: SavingsProdIcon,
      href: "#",
    },
    {
      id: "fees-charges",
      label: "Fees and Charges",
      icon: CoinsIcon,
      href: "#",
    },
    { id: "transactions", label: "Transactions", icon: TransIcon, href: "#" },
    { id: "services", label: "Services", icon: ServicesIcon, href: "#" },
    {
      id: "service-account",
      label: "Service Account",
      icon: ServiceAccIcon,
      href: "#",
    },
    {
      id: "settlements",
      label: "Settlements",
      icon: SettlementsIcon,
      href: "#",
    },
    { id: "reports", label: "Reports", icon: ReportsIcon, href: "#" },
  ],
  settings: [
    {
      id: "preferences",
      label: "Preferences",
      icon: PreferencesIcon,
      href: "#",
    },
    { id: "fees-pricing", label: "Fees and Pricing", icon: FeeIcon, href: "#" },
    { id: "audit-logs", label: "Audit Logs", icon: AuditIcon, href: "#" },
  ],
};
